pipeline {
    agent {
        docker {image 'jenkins/jnlp-slave:latest'}
    }
    tools{
        gradle '7.0.2'
    }
    stages {
        stage('Build') {
            steps {
                sh 'docker --version'
                sh 'gradle assemble'
            }
        }
        stage('Test') {
            steps {
                sh 'gradle test'
            }
        }
        stage('Build Docker image') {
            steps {
                sh 'gradle docker --info'
            }
        }
        stage('Run Docker Image') {
            steps {
                sh 'gradle dockerRun'
            }
        }
    }
}
